### ISSUE TITLE
Include substring completion-style in benchmark

### ISSUE THREAD

**Issue by minad** [axelf4/emacs-completion-bench#1]
`basic` is an outliner since prefix matching is optimized specially. I suggest to additionally include `substring` in your benchmark, since this is the simplest style which uses `completion-regexp-list`.

**Comment by axelf4** [comment]
Good idea, that is what I thought `basic` did but I had gotten them mixed up. Surprised by how much slower `substring` is than `orderless`. Given the search strings used, should not `orderless` be performing the same matching as `substring`?

**Comment by minad** [comment]
Thanks! Interesting that substring is even slower than orderless. Maybe this is because of the inefficient highlighting (completion-pcm--hilit-commonality)? As you are aware, in Vertico and Corfu I hack the completion styles such that highlighting is deferred, so in practice this may matter less. You could also write your own minimal completion styles for the benchmark which don't do highlighting at all (e.g. based on the emacs21 style or the substring style without the highlighting). This should give a better absolute baseline.
